urls.py
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('features', views.features, name='features'),
    path('order', views.order, name='order'),
    path('order/<int:pk>', views.edit_order, name='edit_order'),
    path('contact', views.contact, name='contact'),
]

urlpatterns += staticfiles_urlpatterns()

models.py
from django.db import models


class Size(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Pizza(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    telephone_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    street_address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_zip_code = models.CharField(max_length=100)
    topping1 = models.CharField(max_length=100)
    topping2 = models.CharField(max_length=100)
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    comments = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.topping1 + ', ' + self.topping2

forms.py
from django import forms
from .models import Pizza, Size


# Django ModelForm override widget
# https://stackoverflow.com/questions/9878475/django-modelform-override-widget

class PizzaForm(forms.ModelForm):

    class Meta:
        model = Pizza
        fields = ['first_name', 'last_name', 'telephone_number', 'email', 'street_address',
                  'city', 'state', 'postal_zip_code', 'topping1', 'topping2', 'size', 'comments']
        labels = {'topping1': 'Topping 1',
                  'topping2': 'Topping 2',
                  }
        widgets = {
            'comments': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
        }

views.py
from django.shortcuts import render
from .forms import PizzaForm
from .models import Pizza



def index(request):
    return render(request, 'pizza/index.html')

def about(request):
    return render(request, 'pizza/about.html')

def features(request):
    return render(request, 'pizza/features.html')

def order(request):
    if request.method == "POST":
        filled_form = PizzaForm(request.POST, request.FILES)

        filled_form = PizzaForm(request.POST)
        if filled_form.is_valid():
            created_pizza = filled_form.save()
            created_pizza_pk = created_pizza.id
            note = 'Thanks for ordering! Your %s %s and %s pizza is on its way!' % (
                filled_form.cleaned_data['size'],
                filled_form.cleaned_data['topping1'],
                filled_form.cleaned_data['topping2'],
            )
            filled_form = PizzaForm()
        else:
            created_pizza_pk = None
            note = 'Pizza order has failed. Try again.'
        return render(request, 'pizza/order.html', {'created_pizza_pk': created_pizza_pk, 'pizzaform': filled_form,
                                                    'note': note})
    else:
        form = PizzaForm()
        return render(request, 'pizza/order.html', {'pizzaform': form})

def edit_order(request, pk):
    pizza = Pizza.objects.get(pk=pk)
    form = PizzaForm(instance=pizza)
    if request.method == 'POST':
        filled_form = PizzaForm(request.POST, instance=pizza)
        if filled_form.is_valid():
            filled_form.save()
            form = filled_form
            note = 'Order has been updated.'
            return render(request, 'pizza/edit_order.html', {'note': note, 'pizzaform': form, 'pizza': pizza})
    return render(request, 'pizza/edit_order.html', {'pizzaform': form, 'pizza': pizza})

def contact(request):
    return render(request, 'pizza/contact.html')

templates/pizza/about.html
{% extends 'pizza/base.html' %}

{% block content %}

<h1>About</h1>
<p> Full stack app that allows customers to order pizza online. </p>
{% endblock %}

templates/pizza/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pizza App</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'pizza/assets/favicon.ico' %}"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'pizza/css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'pizza/css/pizza.css' %}" />
  </head>
  <body class="d-flex flex-column min-vh-100">
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'pizza:index' %}">Pizza App</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'pizza:index' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:order' %}">Order Pizza</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:features' %}">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main class="container">
      <div class="row">
        <div class="col">{% block content %} {% endblock %}</div>
      </div>
    </main>

    <!-- Footer-->
    <footer class="py-5 bg-dark mt-auto">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Pizz App 2023</p>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <!-- <script src="js/scripts.js"></script> -->
    <script src="{% static 'pizza/js/scripts.js' %}"></script>
  </body>
</html>

templates/pizza/contact.html
{% extends 'pizza/base.html' %}

{% block content %}

<h1>Contact</h1>

{% endblock %}

templates/pizza/edit_order.html
{% extends 'pizza/base.html' %}

{% block content %}

<h1>Edit Pizza</h1>

<h2>{{ note }}</h2>

<form action="{% url 'pizza:edit_order' pizza.id %}" method="post">
  {% csrf_token %} {{ pizzaform.as_p }}
  <input type="submit" value="Edit Pizza" class="btn btn-secondary btn-lg edit-button"/>
</form>

{% endblock %}

templates/pizza/features.html
{% extends 'pizza/base.html' %} {% block content %}

<h1>Features</h1>
<ul class="list-group">
  <li class="list-group-item">
    A public site allows customers to order pizza online
  </li>
  <li class="list-group-item">
    Administrator site with login page that allows restaurant managers and
    kitchen staff to view and edit customer orders.
  </li>
  <li class="list-group-item">
    Relational database that can help a restaurant scale a business
  </li>
  <li class="list-group-item">
    SMS feature that allows managers to comfirm customer orders
  </li>
</ul>
{% endblock %}

templates/pizza/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pizza App</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'pizza/css/styles.css' %}" />
  </head>
  <body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'pizza:index' %}">Pizza App</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'pizza:index' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:order' %}">Order Pizza</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:features' %}">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizza:contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header - set the background image for the header in the line below-->
    <header
      class="py-5 bg-image-full"
      style="
        background-image: url({% static '/pizza/assets/images/pizza_image_1.jpg' %})">
      <div class="text-center my-5 heading-elements-box">
        <h1 class="text-white fs-3 fw-bolder">Tasty Pizza</h1>
        <p class="text-white-50 mb-0">
          Simply order and we'll take care of everything
        </p>
      </div>
    </header>
    <!-- Content section-->
    <section class="py-5">
      <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h2>Contents About the Pizza Restaurant</h2>
            <p class="lead">
              Diam tincidunt nam fermentum aptent erat metus interdum penatibus,
              parturient risus commodo tempor justo velit quis aliquam,
              sagittis molestie vulputate phasellus quisque tellus sit.
              Varius eleifend non himenaeos tellus aenean vivamus aptent ultricies feugiat,
              amet turpis orci nec mattis at facilisi accumsan cras,
              ultrices imperdiet massa blandit mauris facilisis mus class.
              Neque phasellus diam tempus lacinia bibendum leo dolor curae aliquet interdum felis,
              porttitor nostra fusce turpis curabitur suspendisse feugiat parturient sit ad accumsan consequat,
              aptent fames dignissim dictumst potenti facilisi justo iaculis cubilia maecenas.
              Viverra massa sed euismod sociis venenatis urna fusce bibendum,
              taciti ipsum id a pharetra et cras consequat phasellus,
               nostra augue ultricies vel curabitur lectus egestas.

            Litora aliquam sed lectus dignissim laoreet accumsan mattis viverra,
            curabitur habitasse quisque consectetur placerat venenatis pulvinar duis himenaeos,
            dapibus euismod lorem convallis ultricies integer potenti. Nibh quisque volutpat ullamcorper
            ligula habitant sociis pulvinar, euismod ipsum posuere lacus proin in senectus,
            </p>
            <p class="lead">
               ullamcorper malesuada orci ante. Risus imperdiet eros pulvinar lectus a turpis elementum,
               conubia ante cum penatibus hac fermentum sollicitudin curabitur,
               ornare inceptos habitant urna tellus porta.
               Fusce viverra rhoncus rutrum enim hac felis et volutpat tempor sagittis tempus nibh,
               iaculis donec orci euismod ullamcorper sapien in cras senectus sem gravida.
               Dignissim suspendisse arcu nec pulvinar ultrices et morbi, praesent malesuada venenatis litora diam auctor,
                dapibus eleifend platea sit sem penatibus.
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- Image element - set the background image for the header in the line below-->
    <div
      class="py-5 bg-image-full"
      style="
        background-image: url({% static '/pizza/assets/images/pizza_image_2.jpg' %})">
      <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
      <div style="height: 20rem"></div>
    </div>
    <!-- Content section-->
    <section class="py-5">
      <div class="container my-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h2>More Contents About the Pizza Restaurant</h2>
            <p class="lead">The weekends is better with Pizza</p>
            <p class="lead">
              Nibh est a ut suspendisse tempor enim primis blandit ligula sagittis arcu vitae,
              nunc dictum nec fusce pellentesque nulla fames imperdiet mi neque.
              Fusce duis amet sem varius sed consequat nascetur curabitur,
              convallis conubia tincidunt turpis porttitor augue.
               Iaculis est nisi conubia etiam fusce id tortor habitant nulla tempor pellentesque penatibus habitasse,
                lorem eleifend accumsan neque pharetra curabitur placerat nisl hendrerit mattis felis amet.
                Hac euismod bibendum quam lacinia elementum ante pretium sem tempus,
                fames parturient consequat himenaeos iaculis ullamcorper ultrices laoreet varius,
                setiam quisque porta consectetur at porttitor
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">
          Copyright &copy; Pizza App 2023
        </p>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <!-- <script src="js/scripts.js"></script> -->
    <script src="{% static 'pizza/js/scripts.js' %}"></script>
  </body>
</html>

templates/pizza/order.html
{% extends 'pizza/base.html' %}

{% block content %}

<h1>Order a pizza</h1>
<h2>{{ note }}</h2>
{% if created_pizza_pk %}

<a href="{% url 'pizza:edit_order' created_pizza_pk %}">Edit Your Order</a>

{% endif %}

<form enctype="multipart/form-data" action="{% url 'pizza:order' %}" method="post">
  <form action="{% url 'pizza:order' %}" method="post">
    {% csrf_token %} {{ pizzaform.as_p }}

    <input type="submit" value="Order Pizza" class="btn btn-secondary btn-lg order-button"    />
  </form>
</form>

{% endblock %}